### ISSUE TITLE
[UI] Link to view mint tx on scan doesn't work

### ISSUE THREAD

**Issue by anhntbk08** [tomochain/tomobridgev2#1]
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/2239780/119434108-b0b35a00-bd41-11eb-85f3-0947e8efa20a.png">

**Comment by pqv199x** [comment]
Fixed: https://github.com/tomochain/tomobridgev2/commit/a959a1d3ca5cbd6f2859b25cb4c6bf1a8baf9d71
